### ISSUE TITLE
[BUG]扫码后出错

### ISSUE THREAD

**Issue by TwoY0ung2S1mple** [ztren/COC7dicebot#1]
（还在维护吗）
没有装Ubantu（装了打不开显示crash）
装了python3，系统是win10
通过“用管理员模式运行init文件夹中的setup.cmd文件来安装pip和wxpy。”安装了相关程式
下载了dicebot1.1.0（也尝试了1.0.4）
改了wordstr参数后运行，能显示二维码

扫描二维码登录就会跳出这个error
![image](https://github.com/ztren/CRISPY/assets/143410161/6ea53e03-c510-4a96-95a1-6f6a75d7feca)

**Comment by ztren** [comment]
非常遗憾的，本项目因为微信API规则改变（以及本人学习相关专业早期缺乏经验写出的屎山）已经不再维护。

你可以尝试登录一下[微信网页版](wx.qq.com)，大概率会显示无法登录并且让你下载app，而微信网页版是支持本工具wxpy运行的必要基础。据我所知，目前绝大部分用户已经无法使用微信网页版；这是本项目停止维护的主要原因。

edit：我用无法使用网页版微信的微信号尝试登陆了CRISPY，显示了同样的错误。大概答案已经水落石出了。

感谢您的支持，祝您好运。
